version: 2.1
executors:
  node-executor:
    docker:
      - image: circleci/node:10.15
    working_directory: ~/repo
    environment:
      - GIT_BASE_REVISION: << pipeline.git.base_revision >>
      - GIT_CURRENT_REVISION: << pipeline.git.revision >>
      - NODE_BIN_DIR: "node_modules/.bin"
      - PRERELEASE_COMMIT_HEAD: "chore(prerelease): bump version"
      - RELEASE_COMMIT_HEAD: "chore(release): bump version"
commands:
  add-github-write-key:
    description: "Add GitHub read/write ssh key"
    steps:
      - add_ssh_keys:
          fingerprints:
            - "7e:7e:9e:89:5f:8d:04:99:a1:44:98:e4:55:ac:58:cf"
  set-git-user:
    description: "Set git user in config"
    parameters:
      email:
        type: string
        default: "nakts0123@gmail.com"
      name:
        type: string
        default: "yucj"
    steps:
      - run: git config --global user.email << parameters.email >>
      - run: git config --global user.name << parameters.name >>
  set-npm-auth:
    description: "Set NPM authentication"
    steps:
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
  install-build-deps:
    description: "Install build dependencies"
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-build-{{ checksum "yarn.lock" }}
      - run: yarn
      - save_cache:
          paths:
            - node_modules
            - packages/package-a/node_modules
          key: v1-dependencies-build-{{ checksum "yarn.lock" }}
      
jobs:
  prerelease:
    executor: node-executor
    steps:
      - checkout
      - add-github-write-key
      - set-git-user
      - set-npm-auth
      - install-build-deps
      - run:
          name: "Bump version and publish packages if needed"
          command: |
            # Bump prerelease version and push to origin (distribution files are built at `prepublishOnly` hook)
            # Publish packages
            ${NODE_BIN_DIR}/lerna publish \
              --pre-dist-tag prerelease \
              --conventional-commits \
              --conventional-prerelease \
              --preid rc \
              --include-merged-tags \
              --message "$PRERELEASE_COMMIT_HEAD" \
              --yes

  release:
    executor: node-executor
    steps:
      - checkout
      - add-github-write-key
      - set-git-user
      - set-npm-auth
      - install-build-deps
      - run:
          name: "Bump version and publish packages if needed."
          command: |
            # Bump release version and push to origin (distribution files are built at `prepublishOnly` hook)
            ${NODE_BIN_DIR}/lerna publish \
              --conventional-commits \
              --conventional-graduate \
              --include-merged-tags \
              --message "$RELEASE_COMMIT_HEAD" \
              --yes
            # Push the release to origin/master
            git push origin master

workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      # - check-version-commit
      - release:
          # requires:
          #   - check-version-commit
          filters:
            branches:
              only: release
      - prerelease:
          # requires:
          #   - check-version-commit
          filters:
            branches:
              only: master
